name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run test correct
      run: python -m unittest hello.tests.BaseTest.test_correct
    - name: Run test mistake
      run: python -m unittest hello.tests.BaseTest.test_mistake
